### ISSUE TITLE
CSS files not getting copied to lib abd lib-esm directory

### ISSUE THREAD

**Issue by anil1712** [shnydercom/lerna-typescript-cra-uilib-starter#1]
Hi @shnydercom 

The component CSS files are not getting copied from my-monorepo-ui-lib to my-monorepo-cra-app. So I am getting this error.

```
../my-monorepo-ui-lib/lib-esm/components/card/card.js
Module not found: Can't resolve './card.css
```

**Comment by mayteio** [comment]
TSC doesn't copy files unfortunately. Fortunately, `copyfiles` does. 

The below snippet will copy .woff, .woff2 and .css files.

```
$ cd my-monorepo-ui-lib && yarn add --dev copyfiles

// package.json
...
"scripts": {
    "story": "start-storybook",
    "libbuild": "tsc && tsc --build tsconfig.esm.json && yarn copy",
    "copy": "copyfiles -u 1 src/**/*.woff src/**/*.woff2 src/**/*.css lib && copyfiles -u 1 src/**/*.woff src/**/*.woff2 src/**/*.css lib-esm"
  },
...
```

**Comment by shnydercom** [comment]
I was actually intentionally leaving out the question of how to include css/scss/jss/css-components, because each of those approaches require you to do your build just slightly differently. I'll close this issue for now, if there's a general solution to our css-pain I'll be glad to include it =)
